# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spork < Formula
  desc "Spork CLI — uptime monitoring from your terminal"
  homepage "https://sporkops.com"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sporkops/cli/releases/download/v0.8.0/spork_darwin_amd64.tar.gz"
      sha256 "c260b3af9d12dd656e2e94ea273d322b2f860032c77ff66b394e1cf8af033669"

      define_method(:install) do
        bin.install "spork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sporkops/cli/releases/download/v0.8.0/spork_darwin_arm64.tar.gz"
      sha256 "dc97702de5235ae5caa9c28cf18e9604103095e79abbfc954b10649edbd54f0c"

      define_method(:install) do
        bin.install "spork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sporkops/cli/releases/download/v0.8.0/spork_linux_amd64.tar.gz"
      sha256 "bf5663a43c552725aaa5d25a190486b141e7d121bfcc75c780ed5220aad3a06a"
      define_method(:install) do
        bin.install "spork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sporkops/cli/releases/download/v0.8.0/spork_linux_arm64.tar.gz"
      sha256 "c65fe8a18223741c85ca36ae38f09fe2c21c2354c2ce94284c674dc3b7446f07"
      define_method(:install) do
        bin.install "spork"
      end
    end
  end
end
